[tool.vulture]
exclude = [".venv"]
min_confidence = 80

[tool.bandit]
exclude_dirs = [".venv"]
skips = ["B101"]

[tool.isort]
profile = "black"
line_length = 79
force_single_line = true
skip_gitignore = true
include_trailing_comma = true

[tool.black]
line-length = 79

[tool.flake8]
extend-exclude = [".venv", "*~", "*.swp", "*.pyc", ".mypy_cache", "*.txt", ".gitignore", "*.toml"]
filename = "*.py"

[tool.mypy]
strict = true
python_executable = "python"

[[tool.mypy.overrides]]
module = "prettyprinter.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "cryptography.*"
ignore_missing_imports = true
